import React from 'react'
import styles from '../styles/Home.module.css'
import Head from 'next/head'

export default function about() {
    return (
        <div className={ styles.container }>
                  <Head>
                        <title>About Page</title>
                        <meta name="description" content="Generated by create next app" />
                        <link rel="icon" href="/favicon.ico" />
                    </Head>
            <h1>This is about page</h1>
            <div>
                <a href='/'>
                    <button>Go Home</button>
                </a>
            </div>
        </div>
    )
}
