import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import { useState, useEffect } from 'react'
import { useRouter } from 'next/router'
import Link from 'next/link'


function Redirect ({ to }) {
  const router = useRouter();
  useEffect(() => {router.push(to) }, [to])
  return null
}

export default function Home() {

  const router = useRouter();
  const { query } = router;
  const count = parseInt(query.count || 1)
  console.log(count)
  if (count === 9 ) {
    return <Redirect to='/about'/>
  }

  const [shouldRedirect, setShouldRedirect ] = useState(false);

  if (shouldRedirect) {
    return <Redirect to='/about'/>
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Next Router Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hello <span>World</span>
        </h1>
        <div className={styles.card}>
        <button 
          onClick={() => (window.location.href = "/about")}
        > Native Link </button>
        <a  href="/about">HTML Link</a>

        <button  onClick={() => {
          router.push('/about')
        }}> Router Link </button>

        <Link  href='/about'>
          <a>
            Next Link
          </a>
        </Link>

        <button
          
          onClick={() => setShouldRedirect(true)}
        > 
        Redirect Link 
        </button>

        </div>
        <button
          className={styles.card}
          onClick={() => {
            router.push(`/?count=${ count + 1} `, undefined, { shallow: true })
          }}
        > Increment { count }</button>

      </main>


    </div>
  )
}
